language: java
jdk:
  - openjdk14

codecov: true

sudo: false

env:
  global:
    - CODECOV_TOKEN="e13ef9ec-aae4-486b-b7c6-c6c2a66c82be"

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - mazusik1@gmail.com
    on_success: never # default: change
    on_failure: always # default: always